site_name: BYU CE 547
site_url: https://ce547.readthedocs.io/en/latest/
site_description: Course materials for CE 547 at BYU
site_author: Norm Jones (instructor) and TAs of CE 547 at BYU
repo_url: https://github.com/cce547/
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
  - js/mathjax-config.js
markdown_extensions:
    - attr_list
    - sane_lists
    - md_in_html
    - admonition
    - pymdownx.arithmatex:
        generic: true
theme: readthedocs
extra_css:
  - css/custom.css
nav:
  - Home: index.md
  - Class Resources:
    - Syllabus: resources/syllabus.md
    - GMS Software: resources/gms.md
    - Course Overview: resources/overview/intro_read.md
    - Equation Sheet: resources/eq_sheet.md
    - Exam 1 Study Guide: resources/exam1_study_guide.md
  - Unit 1 - Modeling Fundamentals:
    - Groundwater Modeling Concepts:
        - Pre-Class: unit1/01_modeling/modeling_read.md
    - Hydraulic Head Concepts:
        - Pre-Class: unit1/02_head/head_read.md
        - In-Class: unit1/02_head/head_class.md
        - Homework: unit1/02_head/head_hw.md
    - Darcy's Law:
        - Pre-Class: unit1/03_darcy/darcy_read.md
        - In-Class: unit1/03_darcy/darcy_class.md
        - Homework: unit1/03_darcy/darcy_hw.md
    - Darcy's Law - Layered Systems:
        - Pre-Class: unit1/04_darcy_layered/darcy_layered_read.md
        - In-Class: unit1/04_darcy_layered/darcy_layered_class.md
        - Homework: unit1/04_darcy_layered/darcy_layered_hw.md
    - Governing Equations:
        - Pre-Class (Gov Eqs): unit1/05_goveqs/goveqs_read.md
    - Conceptual Models:
        - Pre-Class: unit1/06_conceptual_models/conceptual_models_read.md
  - Unit 2 - MODFLOW Basics:
    - MODFLOW Organization and Main Packages:
        - Pre-Class: unit2/01_organization/organization_read.md
        - In-Class: unit2/01_organization/organization_class.md
        - Homework: unit2/01_organization/organization_hw.md
    - MODFLOW Case Studies, Part 1:
        - In-Class: unit2/02_study_pt1/study_pt1_class.md
        - Homework: unit2/02_study_pt1/study_pt1_hw.md
    - MODFLOW Optional Packages:
        - Pre-Class: unit2/03_optional_packages/optional_packages_read.md
        - In-Class: unit2/03_optional_packages/optional_packages_class.md
        - Homework: unit2/03_optional_packages/optional_packages_hw.md
    - MODFLOW Case Studies, Part 2:
        - In-Class: unit2/04_study_pt2/study_pt2_class.md
    - 2D Geostatistics:
        - Pre-Class: unit2/05_geostats/geostats_read.md
        - In-Class: unit2/05_geostats/geostats_class.md
        - Homework: unit2/05_geostats/geostats_hw.md
  - Unit 3 - MODFLOW Advanced:
    - MODFLOW Solvers:
        - Pre-Class: unit3/01_solver/solver_read.md
        - In-Class: unit3/01_solver/solver_class.md
    - Regional Models - Conceptual Model Approach:
        - Pre-Class: unit3/02_regional_models/regional_models_read.md
        - In-Class: unit3/02_regional_models/regional_models_class.md
        - Homework: unit3/02_regional_models/regional_models_hw.md
    - MODFLOW Case Studies, Part 3:
        - In-Class: unit3/03_study_pt3/study_pt3_class.md
    - MODFLOW Case Studies, Part 4:
        - In-Class: unit3/04_study_pt4/study_pt4_class.md
        - Homework: unit3/04_study_pt4/study_pt4_hw.md
    - Model Calibration:
        - Pre-Class: unit3/05_calibration/calibration_read.md
        - In-Class: unit3/05_calibration/calibration_class.md
        - Homework: unit3/05_calibration/calibration_hw.md
    - Automated Parameter Estimation:
        - Pre-Class: unit3/06_parameter/parameter_read.md
        - In-Class: unit3/06_parameter/parameter_class.md
        - Homework: unit3/06_parameter/parameter_hw.md
    - Pilot Point Method:
        - Pre-Class: unit3/07_pilot/pilot_read.md
        - In-Class: unit3/07_pilot/pilot_class.md
        - Homework: unit3/07_pilot/pilot_hw.md
    - MODPATH Particle Tracking:
        - Pre-Class: unit3/08_particle/particle_read.md
        - In-Class: unit3/08_particle/particle_class.md
        - Homework: unit3/08_particle/particle_hw.md
    - Stochastic Modeling:
        - Pre-Class: unit3/09_stochastic/stochastic_read.md
        - In-Class: unit3/09_stochastic/stochastic_class.md
        - Homework: unit3/09_stochastic/stochastic_hw.md
    - Transient MODFLOW Simulations:
        - Pre-Class: unit3/10_simulations/simulations_read.md
        - In-Class: unit3/10_simulations/simulations_class.md
        - Homework: unit3/10_simulations/simulations_hw.md
    - Groundwater Sustainability Analysis:
        - Pre-Class: unit3/11_sustainability/sustainability_read.md
        - Homework: unit3/11_sustainability/sustainability_hw.md
    - Boundary Condition Analysis:
        - Pre-Class: unit3/12_boundary_condition/boundary_condition_read.md
        - In-Class: unit3/12_boundary_condition/boundary_condition_class.md
        - Homework: unit3/12_boundary_condition/boundary_condition_hw.md
  - Term Project:
    - Overview: termproject/tpoverview/tp_overview.md
    - Case Study 1: termproject/casestudy1/case_study_1.md
    - Case Study 2: termproject/casestudy2/case_study_2.md
    - Case Study 3: termproject/casestudy3/case_study_3.md
    - Case Study 4: termproject/casestudy4/case_study_4.md
    - Case Study 5: termproject/casestudy5/case_study_5.md
    - Case Study 6: termproject/casestudy6/case_study_6.md